changelog:
    categories:
        - title: "Breaking changes"
          labels:
              - breaking
        - title: "Stack upgrades"
          labels:
              - dependencies
              - upgrade
        - title: "New features"
          labels:
              - enhancement
              - feature
        - title: "Bug fixes"
          labels:
              - bug
              - fix
        - title: "Maintenance"
          labels:
              - chore
              - docs
              - ci
